// <auto-generated />
using System;
using CQRSales.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CQRSales.Infrastructure.Migrations
{
    [DbContext(typeof(SalesContext))]
    [Migration("20260326162733_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CQRSales.Domain.Models.ApplicaitonUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CQRSales.Domain.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ArchivedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchivedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IArchived")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DescriptionAr = "أدوية لتخفيف الألم",
                            DescriptionEn = "Medicines used to relieve pain",
                            IArchived = false,
                            NameAr = "مسكنات الألم",
                            NameEn = "Pain Relief"
                        },
                        new
                        {
                            ID = 2,
                            DescriptionAr = "مكملات غذائية لتحسين الصحة",
                            DescriptionEn = "Supplements and vitamins for better health",
                            IArchived = false,
                            NameAr = "فيتامينات ومكملات",
                            NameEn = "Vitamins & Supplements"
                        },
                        new
                        {
                            ID = 3,
                            DescriptionAr = "أدوية لعلاج العدوى البكتيرية",
                            DescriptionEn = "Drugs used to treat bacterial infections",
                            IArchived = false,
                            NameAr = "مضادات حيوية",
                            NameEn = "Antibiotics"
                        },
                        new
                        {
                            ID = 4,
                            DescriptionAr = "لعلاج نزلات البرد والانفلونزا",
                            DescriptionEn = "Medicines for cold and flu symptoms",
                            IArchived = false,
                            NameAr = "أدوية البرد والانفلونزا",
                            NameEn = "Cold & Flu"
                        },
                        new
                        {
                            ID = 5,
                            DescriptionAr = "منتجات العناية بالبشرة والجمال",
                            DescriptionEn = "Skin care and beauty products",
                            IArchived = false,
                            NameAr = "مستحضرات تجميل",
                            NameEn = "Cosmetics"
                        });
                });

            modelBuilder.Entity("CQRSales.Domain.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchivedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchivedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IArchived")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Cairo, Egypt",
                            BirthDate = new DateTime(1995, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IArchived = false,
                            NameAr = "أحمد علي",
                            NameEn = "Ahmed Ali",
                            PhoneNumber = "01012345678"
                        },
                        new
                        {
                            ID = 2,
                            Address = "Alexandria, Egypt",
                            BirthDate = new DateTime(1998, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IArchived = false,
                            NameAr = "سارة محمد",
                            NameEn = "Sara Mohamed",
                            PhoneNumber = "01098765432"
                        },
                        new
                        {
                            ID = 3,
                            Address = "Giza, Egypt",
                            BirthDate = new DateTime(1990, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IArchived = false,
                            NameAr = "خالد إبراهيم",
                            NameEn = "Khaled Ibrahim",
                            PhoneNumber = "01122334455"
                        },
                        new
                        {
                            ID = 4,
                            Address = "Mansoura, Egypt",
                            BirthDate = new DateTime(1993, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IArchived = false,
                            NameAr = "منى عبد الرحمن",
                            NameEn = "Mona Abdelrahman",
                            PhoneNumber = "01255667788"
                        },
                        new
                        {
                            ID = 5,
                            Address = "Tanta, Egypt",
                            BirthDate = new DateTime(1999, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IArchived = false,
                            NameAr = "يوسف حسن",
                            NameEn = "Youssef Hassan",
                            PhoneNumber = "01066554433"
                        });
                });

            modelBuilder.Entity("CQRSales.Domain.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ArchivedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchivedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOrder")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IArchived")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalOrder")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CQRSales.Domain.Models.OrderProduct", b =>
                {
                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.Property<double>("ProductTotalPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("CQRSales.Domain.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ArchivedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchivedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("BuyPrice")
                        .HasColumnType("float");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IArchived")
                        .HasColumnType("bit");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<double>("SalePrice")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BuyPrice = 10.0,
                            CategoryID = 1,
                            DescriptionAr = "مسكن للألم وخافض للحرارة",
                            DescriptionEn = "Pain reliever and fever reducer",
                            IArchived = false,
                            MinQuantity = 20,
                            NameAr = "بانادول",
                            NameEn = "Panadol",
                            Quantity = 200.0,
                            SalePrice = 15.0
                        },
                        new
                        {
                            ID = 2,
                            BuyPrice = 12.0,
                            CategoryID = 1,
                            DescriptionAr = "مسكن للآلام والالتهابات",
                            DescriptionEn = "Pain reliever and anti-inflammatory",
                            IArchived = false,
                            MinQuantity = 15,
                            NameAr = "بروفين",
                            NameEn = "Brufen",
                            Quantity = 150.0,
                            SalePrice = 18.0
                        },
                        new
                        {
                            ID = 3,
                            BuyPrice = 25.0,
                            CategoryID = 2,
                            DescriptionAr = "مكمل غذائي لتعزيز المناعة",
                            DescriptionEn = "Dietary supplement to boost immunity",
                            IArchived = false,
                            MinQuantity = 10,
                            NameAr = "فيتامين سي",
                            NameEn = "Vitamin C",
                            Quantity = 100.0,
                            SalePrice = 35.0
                        },
                        new
                        {
                            ID = 4,
                            BuyPrice = 30.0,
                            CategoryID = 2,
                            DescriptionAr = "مكمل للعظام والأسنان",
                            DescriptionEn = "Calcium supplement for bones and teeth",
                            IArchived = false,
                            MinQuantity = 15,
                            NameAr = "كالسيوم دي",
                            NameEn = "Calcium D",
                            Quantity = 120.0,
                            SalePrice = 45.0
                        },
                        new
                        {
                            ID = 5,
                            BuyPrice = 18.0,
                            CategoryID = 3,
                            DescriptionAr = "مضاد حيوي واسع المدى",
                            DescriptionEn = "Broad-spectrum antibiotic",
                            IArchived = false,
                            MinQuantity = 10,
                            NameAr = "أموكسيل",
                            NameEn = "Amoxil",
                            Quantity = 80.0,
                            SalePrice = 28.0
                        },
                        new
                        {
                            ID = 6,
                            BuyPrice = 22.0,
                            CategoryID = 3,
                            DescriptionAr = "مضاد حيوي لعلاج العدوى",
                            DescriptionEn = "Antibiotic for bacterial infections",
                            IArchived = false,
                            MinQuantity = 8,
                            NameAr = "سيبروفلوكساسين",
                            NameEn = "Ciprofloxacin",
                            Quantity = 90.0,
                            SalePrice = 35.0
                        },
                        new
                        {
                            ID = 7,
                            BuyPrice = 10.0,
                            CategoryID = 4,
                            DescriptionAr = "لعلاج نزلات البرد والأنفلونزا",
                            DescriptionEn = "Cold and flu medicine",
                            IArchived = false,
                            MinQuantity = 15,
                            NameAr = "فلودريكس",
                            NameEn = "Fludrex",
                            Quantity = 160.0,
                            SalePrice = 15.0
                        },
                        new
                        {
                            ID = 8,
                            BuyPrice = 9.0,
                            CategoryID = 4,
                            DescriptionAr = "لعلاج أعراض البرد والاحتقان",
                            DescriptionEn = "For cold and nasal congestion relief",
                            IArchived = false,
                            MinQuantity = 20,
                            NameAr = "كونجستال",
                            NameEn = "Congestal",
                            Quantity = 180.0,
                            SalePrice = 14.0
                        },
                        new
                        {
                            ID = 9,
                            BuyPrice = 20.0,
                            CategoryID = 5,
                            DescriptionAr = "مرطب للبشرة الجافة",
                            DescriptionEn = "Moisturizing cream for dry skin",
                            IArchived = false,
                            MinQuantity = 25,
                            NameAr = "مرطب نيفيا",
                            NameEn = "Nivea Cream",
                            Quantity = 250.0,
                            SalePrice = 30.0
                        },
                        new
                        {
                            ID = 10,
                            BuyPrice = 15.0,
                            CategoryID = 5,
                            DescriptionAr = "غسول يومي للبشرة",
                            DescriptionEn = "Daily face cleanser",
                            IArchived = false,
                            MinQuantity = 20,
                            NameAr = "غسول الوجه",
                            NameEn = "Face Wash",
                            Quantity = 220.0,
                            SalePrice = 25.0
                        });
                });

            modelBuilder.Entity("CQRSales.Domain.Models.Stock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ArchivedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchivedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IArchived")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalMoney")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DescriptionAr = "مخزون رئيسي في القاهرة",
                            DescriptionEn = "Main stock located in Cairo",
                            IArchived = false,
                            NameAr = "مخزون القاهرة",
                            NameEn = "Cairo Stock",
                            TotalMoney = 50000.0
                        },
                        new
                        {
                            ID = 2,
                            DescriptionAr = "مخزون فرعي في الإسكندرية",
                            DescriptionEn = "Secondary stock in Alexandria",
                            IArchived = false,
                            NameAr = "مخزون الإسكندرية",
                            NameEn = "Alexandria Stock",
                            TotalMoney = 30000.0
                        },
                        new
                        {
                            ID = 3,
                            DescriptionAr = "مخزون خاص بالجيزة",
                            DescriptionEn = "Giza local stock",
                            IArchived = false,
                            NameAr = "مخزون الجيزة",
                            NameEn = "Giza Stock",
                            TotalMoney = 25000.0
                        },
                        new
                        {
                            ID = 4,
                            DescriptionAr = "مخزون احتياطي في المنصورة",
                            DescriptionEn = "Backup stock in Mansoura",
                            IArchived = false,
                            NameAr = "مخزون المنصورة",
                            NameEn = "Mansoura Stock",
                            TotalMoney = 15000.0
                        },
                        new
                        {
                            ID = 5,
                            DescriptionAr = "مخزون محلي في طنطا",
                            DescriptionEn = "Local stock in Tanta",
                            IArchived = false,
                            NameAr = "مخزون طنطا",
                            NameEn = "Tanta Stock",
                            TotalMoney = 20000.0
                        });
                });

            modelBuilder.Entity("CQRSales.Domain.Models.StockDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ArchivedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchivedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IArchived")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("StockID")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("StockID");

                    b.ToTable("StockDetails");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CQRSales.Domain.Models.Order", b =>
                {
                    b.HasOne("CQRSales.Domain.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CQRSales.Domain.Models.OrderProduct", b =>
                {
                    b.HasOne("CQRSales.Domain.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CQRSales.Domain.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CQRSales.Domain.Models.Product", b =>
                {
                    b.HasOne("CQRSales.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CQRSales.Domain.Models.StockDetails", b =>
                {
                    b.HasOne("CQRSales.Domain.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID");

                    b.HasOne("CQRSales.Domain.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CQRSales.Domain.Models.ApplicaitonUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CQRSales.Domain.Models.ApplicaitonUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CQRSales.Domain.Models.ApplicaitonUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CQRSales.Domain.Models.ApplicaitonUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CQRSales.Domain.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CQRSales.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("CQRSales.Domain.Models.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
